れあdめ 更新！
GiganticMinecraft/SeichiAssist-ExternalLib pull request #7
Opened 2020-10-17 13:34 UTC by Megumiso

今起きました！

2020-10-17 13:41 UTC, unchama commented
おはようございます！

2020-10-17 13:47 UTC, unchama requested changes

2020-10-17 13:47 UTC, unchama commented on plugins/ColoredSigns/README.md
> +リスポーン位置を変更するプラグイン
これは本当ですか？

2020-10-17 13:47 UTC, unchama commented on plugins/PlugMan/README.md
> +PlaceholderのAPI
pluginの情報を参照、pluginの個別無効化、有効化、リロードの実施、plugin一覧をテキストファイルでdumpすることができる

2020-10-20 01:05 UTC, Megumiso commented
コピペしたものがそのままになっててワロタ

2020-10-20 03:35 UTC, unchama approved these changes
LGTM. aizaimasu.

2020-10-20 03:36 UTC, merged